/*var notes = 
{
	c3: {v:1},
	d3: {v:1},
	e3: {v:1},
	f3: {v:1},
	g3: {v:1},
	a3: {v:1},
	b3: {v:1},
	cd3: {v:1},
	de3: {v:1},
	fg3: {v:1},
	ga3: {v:1},
	ab3: {v:1},
	c4: {v:1},
	d4: {v:1},
	e4: {v:1},
	f4: {v:1},
	g4: {v:1},
	a4: {v:1},
	b4: {v:1},
	cd4: {v:1},
	de4: {v:1},
	fg4: {v:1},
	ga4: {v:1},
	ab4: {v:1},
	c5: {v:1},
	d5: {v:1},
	e5: {v:1},
	f5: {v:1},
	g5: {v:1},
	a5: {v:1},
	b5: {v:1},
	cd5: {v:1},
	de5: {v:1},
	fg5: {v:1},
	ga5: {v:1},
	ab5: {v:1}
};
*/

var ass = [
	{value: "d4", activeClass: "white", color: "#ff7f50"},
	{value: "a4", activeClass: "white", color: "#0000ff"},
	{value: "f4", activeClass: "white", color: "#008000"},
	{value: "e4", activeClass: "white", color: "#ffff00"},
	{value: "g4", activeClass: "white", color: "#00bfff"},
	{value: "c4", activeClass: "white", color: "#dc143c"},
	{value: "b4", activeClass: "white", color: "#9400d3"},
	{value: "fg4", activeClass: "black", color: "linear-gradient(to right, #008000, #00bfff)"},
	{value: "cd4", activeClass: "black", color: "linear-gradient(to right, #dc143c, #ff7f50)"},
	{value: "ab4", activeClass: "black", color: "linear-gradient(to right, #0000ff, #9400d3)"},
	{value: "de4", activeClass: "black", color: "linear-gradient(to right, #ff7f50, #ffff00)"},
	{value: "ga4", activeClass: "black", color: "linear-gradient(to right, #00bfff, #0000ff)"},
	{value: "b3", activeClass: "white", color: "#4b0082"},
	{value: "c5", activeClass: "white", color: "#ff0000"},
	{value: "ab3", activeClass: "black", color: "linear-gradient(to right, #00008b, #4b0082)"},
	{value: "cd5", activeClass: "black", color: "linear-gradient(to right, #ff0000, #ffa500)"},
	{value: "a3", activeClass: "white", color: "#00008b"},
	{value: "d5", activeClass: "white", color: "#ffa500"},
	{value: "ga3", activeClass: "black", color: "linear-gradient(to right, #00bfff, #00008b)"},
	{value: "de5", activeClass: "black", color: "linear-gradient(to right, #ffa500, #f0e68c)"},
	{value: "g3", activeClass: "white", color: "#00bfff"},
	{value: "e5", activeClass: "white", color: "#f0e68c"},
	{value: "fg3", activeClass: "black", color: "linear-gradient(to right, #006400, #00bfff)"},
	{value: "f5", activeClass: "white", color: "#9acd32"},
	{value: "f3", activeClass: "white", color: "#006400"},
	{value: "fg5", activeClass: "black", color: "linear-gradient(to right, #9acd32, #7fffd4)"},
	{value: "e3", activeClass: "white", color: "#ffd700"},
	{value: "g5", activeClass: "white", color: "#7fffd4"},
	{value: "de3", activeClass: "black", color: "linear-gradient(to right, #d2691e, #ffd700)"},
	{value: "ga5", activeClass: "black", color: "linear-gradient(to right, #7fffd4, #6495ed)"},
	{value: "d3", activeClass: "white", color: "#d2691e"},
	{value: "a5", activeClass: "white", color: "#6495ed"},
	{value: "cd3", activeClass: "black", color: "linear-gradient(to right, #8b0000, #d2691e)"},
	{value: "ab5", activeClass: "black", color: "linear-gradient(to right, #6495ed, #ba55d3)"},
	{value: "c3", activeClass: "white", color: "#8b0000"},
	{value: "b5", activeClass: "white", color: "#ba55d3"}
];
